### ISSUE TITLE
Cloud assembly schema version mismatch

### ISSUE THREAD

**Issue by willholt-tb** [sv-oss/cdk-cloudone-conformity-scan-action#2]
I'm getting the following error in the CI build for my React microsite:

```
Run sv-oss/cdk-cloudone-conformity-scan-action@main
Error: Cloud assembly schema version mismatch: Maximum schema version supported is 20.0.0, but found 21.0.0
```

Link to the build: https://github.com/service-victoria/react-seniors-digital-token/runs/8183042172?check_suite_focus=true#step:6:24

I'm using CDK version `2.39.1`.

It seems that CDK might be trying to use a schema version (21.0.0) that conformity scan doesn't yet support?

**Comment by NickIannelli** [comment]
@willholt-tb - not sure if you were notified of this, but this has now been resolved. Feel free to upgrade to the latest CDK for relevant repo's.

**Comment by willholt-tb** [comment]
Cheers @NickIannelli, thanks for fixing this 👍
